name: get-latest-data

on:
  workflow_dispatch:
  schedule:
    # 毎日21:00分に実行
    - cron: '00 14 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fetch
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          WEB_HOOK_URL: ${{ secrets.WEB_HOOK_URL }}
          TWITTER_ID: ${{ secrets.TWITTER_ID }}
          SUBTEAM_ID: ${{ secrets.SUBTEAM_ID }}
        run: |
          pip install -r requirements.txt
          python3 update.py
      - name: commit and push
        run: |
          git config --global user.email "workflow@example.com"
          git config --global user.name "workflow user"
          git add data/data.csv
          git commit -m 'update data' && git push ${REPO} HEAD:${{github.event.pull_request.head.ref}} || true
          git push